Created a responsive design (a mobile version)
dlwub/My-personal-portfolio-Mobile-Version- pull request #2
Opened 2022-06-30 11:55 UTC by dlwub

Hello @Nemwel-Boniface:
I found your review very helpful.
- Updated index.html and style.css files to make the design responsive.
- Used semantically correct tags in the html files
- Updated the required images
- Gave different states (i.e hover, active, pressed) for the "Start collaboration" button
Please kindly check my work.

2022-06-30 12:06 UTC, Nemwel-Boniface commented
Hello @dlwub . I am glad that you found my review very insightful. 
- However, Kindly note that you were supposed to make the changes on the same branch and not open a new one.
- Also, make sure that the linters are passing before you submit it for re-review.

I wish you the best of luck and #happycoding! :partying_face:

2022-06-30 20:14 UTC, dlwub commented
Updated the index.html and the CSS file to include the image as a background image instead of as img file.

2022-06-30 20:31 UTC, vickymarz requested changes
Hi @dlwub , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project that does not have linters setup. Please kindly make sure you don't open a new pull request for your submissions.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-30 21:28 UTC, dlwub commented
I setup Linters.

2022-06-30 22:49 UTC, BertrandConxy requested changes
Hi @dlwub , 

Great work on making the changes requested by a previous reviewers👏 
**NOTE: You should have not opened a new PR. Rather you should have pushed the requested changes  to the pull request #1 and request another review using it. You only open a new pull request when you are told to do so 💡**
I really appreciate you effort in implementing changes requested by previous reviewers, but there are still some which aren't addressed yet. You are so close 🏃‍♂️ 

 ## Highlights 💪 
- All linters are passing
- Good commit messages
- Descriptive PR
- project works well on my PC

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me  @BertrandConxy  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 22:49 UTC, BertrandConxy commented on index.html
> +            </section>
- [ ] While the design looks great 👏 💯 , it is advisable to use the correct semantic tags so that the search engines and screen reader devices will get enough information to interpret your website well. As requested by the previous reviewer in the pull request #1. Please consider replacing the section tag with `class='toolbar'` to just `<header>` tag. Note that it can still possess that class 😃 so that it doesn't affect your styles.

2022-06-30 22:49 UTC, BertrandConxy commented on index.html
> +                </svg>
- [ ] [OPTIONAL] you also need to wrap again this hamburger icon  in the `nav` tag because in the end it will be holding the navigation links 💡

2022-06-30 22:49 UTC, BertrandConxy commented on index.html
> +                <img class="geomerty_1" src="images/image_geometry_1.png" alt="Geometry Image One">
- [ ] [OPTIONAL] This is supposed to be wrapped into the `<a>` tag which redirects the user to the home page. It is a convention that the website logos direct users to the homepage.

2022-06-30 22:49 UTC, BertrandConxy commented on style.css
> +    width: 100%;
- [ ] Your button looks great 👏. However, as requested by the previous reviewer in pull request #1, you have to implement the button interaction. Like how the button appears when you hover on it or when you click on it.  Below is a screenshot that he shared 👇 
![image](https://user-images.githubusercontent.com/90222110/176789729-435c125a-ef88-481d-ad19-c40a8a1b342b.png)

💡 HINT: The way you do it. There are what we call `pseudo-classes` in CSS. These behave like classes but they are not truly. However, they help us implement the styles to our element base on its state.  For example, if we want to give style to the button when it is hovered, we will do 
```bash
.btn:hover {
/**_ADD YOUR STYLES HERE_**/
}
```
Please consider reading this [documentation](https://www.freecodecamp.org/news/css-button-style-hover-color-and-background/#:~:text=How%20to%20Style%20Button,Conclusion) which gives more detailed information about button states and how to style them.

2022-07-01 03:51 UTC, dlwub commented
Included all the requested changes.

2022-07-01 04:10 UTC, Ismailco approved these changes
### Hi @dlwub, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 04:10 UTC, Ismailco commented on index.html
> +        <section class="container">
- [ ] [OPTIONAL] Kindly remove this `section` tag it has no purpose here, also it will reduce your website SEO score

2022-07-01 07:15 UTC, merged