A pull request for a desktop version of a personal portfolio site
dlwub/My-personal-portfolio-Mobile-Version- pull request #8
Opened 2022-07-14 15:14 UTC by dlwub

- Used media queries with a break-point of 768px to create a responsive design that works on all devices.

2022-07-14 16:43 UTC, codecaiine requested changes
Hi @dlwub , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- Clean code :heavy_check_mark:  
- Great UI :heavy_check_mark:

## Required Changes ♻️

- [ ] Please remove the **Linters disable** statement in your styling. Because ` Linters` helps developers to write clean codes and adapt best practices when writing the code.  You just need to export it as the default code. :+1: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 16:43 UTC, codecaiine commented on index.html
> +                    </div>
- [ ] Well done so far but I think you should use a `button` tag instead of using a simple image because this is an action to get your CV :+1: Also, try to adjust the `padding` to make it looks like Figma template.

2022-07-14 16:43 UTC, codecaiine commented on index.html
> +                </section>
- [ ] Please add increase your `padding` to your about technologies lists, otherwise, try your best to make it similar to the template. :smile: 

### Figma template
![Screenshot from 2022-07-14 16-04-17](https://user-images.githubusercontent.com/6615394/179026789-ab5d8e86-55b4-42ca-94ca-87dad79c7033.png)

### Your project
![Screenshot from 2022-07-14 16-03-27](https://user-images.githubusercontent.com/6615394/179026813-633e5f93-d721-445e-a9dd-1bf36aa2277f.png)

2022-07-14 16:43 UTC, codecaiine commented on index.html
> +            </section>
- [ ]  Please check the `font weight`  of your **Get starting** text, it seems different from the Figma template, check the comparison below and adjust it :point_down: 

- [ ] Please check your different input label text `color` and `position`, looks different try your best to make it similar to the template. :+1: 


### Figma template
![Screenshot from 2022-07-14 15-50-24](https://user-images.githubusercontent.com/6615394/179024345-f8644666-5b56-43d3-b2a7-c9b9c7a28bbf.png)

### Your project
![Screenshot from 2022-07-14 15-50-02](https://user-images.githubusercontent.com/6615394/179024356-9152ea4a-c126-493a-8af4-bb77af8bdeb8.png)

2022-07-14 16:43 UTC, codecaiine commented on index.html
> +                </ul>
- [ ] Kindly ensure you conform to the Figma template for the footer social media. it is found at the far right when it should have a used `padding/ margin` space. :+1: 

### Figma template
![Screenshot from 2022-07-14 15-49-14](https://user-images.githubusercontent.com/6615394/179023913-bd010da4-ea3e-405d-a8a2-cc42e855c267.png)

### Your template
![Screenshot from 2022-07-14 15-48-55](https://user-images.githubusercontent.com/6615394/179023920-a02b8ad6-db73-4bc6-bfce-b75a54fbda85.png)

2022-07-14 16:43 UTC, codecaiine commented on README.md
> +Below 768px the mobile version of the site appears and above 768px the desktop version is presented.
- [ ] It is good that you add a README File but it is not completed because all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) are missing :cry: . Please make it descriptive and professional by updating it and don't with the name and details of the people involved in this project, add the getting starting section with explicit steps on how to clone and run your project locally, as this will be of help to non-technical users. :+1:

2022-07-15 16:28 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @peterboro 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 16:28 UTC, tresorsawasawa commented on index.html
> +            </section>
- [ ] As mentioned by the previous reviewer, kindly make sure this section sticks to the Figma template design(especially the inputs text paddings, fonts,...)
### Figma design
![Screenshot from 2022-07-15 17-53-33](https://user-images.githubusercontent.com/83042742/179262782-d462515c-09c8-42b7-b95c-d593e809d584.png)

### Your design
![Screenshot from 2022-07-15 17-55-04](https://user-images.githubusercontent.com/83042742/179263214-896038f8-2210-4ce0-af1a-dadb0a794bca.png)

2022-07-15 16:28 UTC, tresorsawasawa commented on README.md
> +
- [ **OPTIONAL** ] **IMPORTANT:** I think it would be better to replace the `(https://livedemo.com)` link with your deployed page link so the user can easily access the live demo and the current link is broken.

2022-07-15 16:28 UTC, tresorsawasawa commented on README.md
> +Below 768px the mobile version of the site appears and above 768px the desktop version is presented.
- [ **OPTIONAL** ] **Important:** I suggest you improve again your project's description to make it more meaningful about the project content and be professional. You can take a look at this **[template](https://github.com/tresorsawasawa/MyPortfolio/blob/develop/README.md)** and improve other sections of your README.

2022-07-15 21:40 UTC, algerina approved these changes
Hi @dlwub , 
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media3.giphy.com/media/T8ZP9P7efQ8cE/giphy.gif"/>
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-15 22:24 UTC, merged